services:
  redis:
    image: redis:7-alpine
    container_name: placement_redis
    restart: always
    ports:
      - "6378:6379"

  web:
    build: .
    container_name: placement_django
    working_dir: /app/backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    container_name: placement_celery
    working_dir: /app/backend
    command: celery -A PlacementReady worker -l info --concurrency=2
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    depends_on:
      - redis
