# Generated by Django 4.2.30 on 2026-06-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_rawscrapedcontent_remove_question_question_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveSmallIntegerField(default=5)),
                ('questions_answered', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_possible_score', models.FloatField(default=10.0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('question_types', models.JSONField(default=list, help_text="List of question types e.g. ['DSA_CODING', 'SYSTEM_DESIGN']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('candidate_answer', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('missed_concepts', models.JSONField(blank=True, default=list)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('EVALUATED', 'Evaluated'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_appearances', to='companies.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['session', 'order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
