# Generated by Django 6.0.4 on 2026-04-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('OA', 'Online Assessment'), ('INTERVIEW', 'Technical/HR Interview')], max_length=20)),
                ('batch_year', models.IntegerField(blank=True, null=True)),
                ('source_platform', models.CharField(max_length=100)),
                ('source_url', models.URLField(unique=True)),
                ('raw_text', models.TextField()),
                ('extracted_dsa_questions', models.JSONField(blank=True, default=list)),
                ('extracted_core_topics', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_vectorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='companies.company')),
            ],
        ),
    ]
