# Generated by Django 4.2.30 on 2026-05-27 17:53

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('question_type', models.CharField(choices=[('DSA_CODING', 'DSA Coding Problem'), ('DSA_THEORY', 'DSA Theory / Concept'), ('OS', 'Operating Systems'), ('DBMS', 'Database Management Systems'), ('NETWORKS', 'Computer Networks'), ('SYSTEM_DESIGN', 'System Design')], db_index=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Raw scraped text. May contain noise (ads, navigation).')),
                ('interview_question', models.TextField(blank=True, help_text='LLM-cleaned version phrased as an interviewer would ask it.')),
                ('interview_answer', models.TextField(blank=True, help_text='LLM-written reference answer in conversational interview style.')),
                ('question_type', models.CharField(choices=[('DSA_CODING', 'DSA Coding Problem'), ('DSA_THEORY', 'DSA Theory / Concept'), ('OS', 'Operating Systems'), ('DBMS', 'Database Management Systems'), ('NETWORKS', 'Computer Networks'), ('SYSTEM_DESIGN', 'System Design')], db_index=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(choices=[('LC', 'LeetCode'), ('GFG', 'GeeksForGeeks'), ('GENERATED', 'LLM Generated')], default='GFG', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Original scraped URL if applicable.')),
                ('status', models.CharField(choices=[('SCRAPED', 'Scraped — raw text, not yet LLM-processed'), ('PROCESSED', 'LLM has formatted question + written answer'), ('EMBEDDED', 'Embedding computed, ready for semantic search'), ('FAILED', 'Processing failed — see error_log')], db_index=True, default='SCRAPED', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='Captured exception text if LLM/embedding step failed.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='768-dim Gemini embedding for semantic similarity search.', null=True)),
                ('is_duplicate', models.BooleanField(default=False, help_text='Flagged true if cosine similarity > 0.95 to an existing question.')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='How many mock interviews have included this question.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, help_text='Companies this question has been asked at.', related_name='questions', to='companies.company')),
                ('topics', models.ManyToManyField(blank=True, help_text="Fine-grained topic tags e.g. 'Binary Search', 'SQL Joins'.", related_name='questions', to='companies.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question_type', 'status'], name='companies_q_questio_f89d33_idx'), models.Index(fields=['source', 'status'], name='companies_q_source_89e6f3_idx'), models.Index(fields=['is_duplicate'], name='companies_q_is_dupl_4899ae_idx')],
            },
        ),
    ]
