# Generated by Django 4.2.30 on 2026-05-29 16:27

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='384-dim HF embedding for semantic similarity search.', null=True),
        ),
    ]
