# Generated by Django 6.0.4 on 2026-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementexperience',
            name='target_role',
            field=models.CharField(default='Software Engineer', max_length=100),
        ),
    ]
