# Generated by Django 6.0.4 on 2026-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_placementexperience_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementexperience',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
