# Generated by Django 4.2.30 on 2026-05-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_question_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_tags',
            field=models.CharField(blank=True, default='', help_text="Comma-separated topic tags auto-classified by LLM (e.g., 'binary-search,dynamic-programming')", max_length=500),
        ),
    ]
