# Generated by Django 4.2.30 on 2026-06-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_question_topic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='Original scraped URL', unique=True)),
                ('raw_text', models.TextField(help_text='Full raw scraped content')),
                ('company', models.CharField(blank=True, help_text='Company mentioned in the post', max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Scraped Content',
                'verbose_name_plural': 'Raw Scraped Contents',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='raw_source',
            field=models.ForeignKey(blank=True, help_text='Link to original scraped content. Null for LLM-generated questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='companies.rawscrapedcontent'),
        ),
    ]
