# Generated by Django 4.2.30 on 2026-05-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_placementexperience_is_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementexperience',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placementexperience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placementexperience',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
