# Generated by Django 4.2.30 on 2026-05-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_placementexperience_content_hash_alter_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementexperience',
            name='metadata',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='placementexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='placementexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp', null=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table='pr_company',
        ),
        migrations.AlterModelTable(
            name='placementexperience',
            table='pr_placement_experience',
        ),
    ]
