# Generated by Django 4.2.30 on 2026-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_placementexperience_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_trend_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placementexperience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
