# Generated by Django 4.2.30 on 2026-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rawscrapedcontent_remove_question_question_text_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='questions_attempted',
            field=models.ManyToManyField(blank=True, related_name='users_attempted', to='companies.question'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questions_failed',
            field=models.ManyToManyField(blank=True, related_name='users_failed', to='companies.question'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questions_passed',
            field=models.ManyToManyField(blank=True, related_name='users_passed', to='companies.question'),
        ),
    ]
