# Generated by Django 4.2.30 on 2026-05-22 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_placementexperience_content_hash_alter_company_id_and_more'),
        ('users', '0002_alter_user_id_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='batch_year',
            field=models.IntegerField(blank=True, help_text='Graduation Year', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_role',
            field=models.CharField(default='Software Engineer', help_text='Target Placement Role', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User Biography', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp', null=True)),
                ('notes', models.TextField(blank=True, help_text='Private notes on this experience', null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.placementexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'experience')},
            },
        ),
    ]
